trigger:
  branches:
    include:
      - main   # pipeline déclenché sur push vers main

pool:
  name: 'Default'

variables:
  imageName: 'site5g'
  imageTag: '$(Build.BuildId)'

steps:
# 1️⃣ Checkout du code
- checkout: self

# 2️⃣ Build Docker Image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'acr-test'   # Service connection ACR
    repository: '$(imageName)'
    command: 'build'
    dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)

# 3️⃣ Push Docker Image vers ACR
- task: Docker@2
  displayName: 'Push Docker Image to ACR'
  inputs:
    containerRegistry: 'acr-test'   # Service connection ACR
    repository: '$(imageName)'
    command: 'push'
    tags: |
      $(imageTag)


