trigger:
  branches:
    include:
      - azure-pipelines

resources:
  repositories:
    - repository: GitHub   # an internal alias
      type: github
      name: kaoutheeramdouni/Site5g-PFE
      ref: refs/heads/azure-pipelines
      endpoint: GitHub  # GitHub service connection in DevOps

pool:
  name: 'Default'  # your self-hosted agent pool

variables:
  imageName: 'kaoutheeramdouni/site5g'
  imageTag: '$(Build.BuildId)'
  fullImageName: 'acrpfe2025uvt.azurecr.io/$(imageName):$(imageTag)'

steps:
# 1️⃣ Checkout GitHub repo
- checkout: GitHub
  displayName: 'Checkout GitHub repository'

# 2️⃣ Build Docker Image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'acr-test'
    repository: '$(imageName)'
    command: 'build'
    dockerfile: 'Dockerfile'  # adjust if your Dockerfile is in a subfolder
    buildContext: '.'
    tags: |
      $(imageTag)

# 3️⃣ Push Docker Image to DockerHub
- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'acr-test'
    repository: '$(imageName)'
    command: 'push'
    tags: |
      $(imageTag)


- task: KubernetesManifest@0
  displayName: 'Deploy to AKS Engine'
  inputs:
    action: deploy
    kubernetesServiceEndpoint: 'AKS_ENGINE-NEW'   # le service connection
    namespace: 'default'
    manifests: |
      K8s/deployment.yaml
    containers: |
      acrpfe2025uvt.azurecr.io/kaoutheeramdouni/site5g:$(Build.BuildId)
