apiVersion: apps/v1
kind: Deployment
metadata:
  name: site5g-deployment
  labels:
    app: site5g
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site5g
  template:
    metadata:
      labels:
        app: site5g
    spec:
      containers:
      - name: site5g-container
        image: acrpfe2025uvt.azurecr.io/kaoutheeramdouni/site5g:41
        ports:
        - containerPort: 80
      imagePullSecrets:       # <-- ajout de ton secret ACR
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: site5g-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # LB interne
spec:
  type: LoadBalancer
  selector:
    app: site5g
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
